# Generated by Django 3.1.13 on 2021-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsmr_datalogger', '0030_override_telegram_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataloggersettings',
            name='dsmr_version',
            field=models.IntegerField(choices=[(4, 'Netherlands - DSMR version 4/5 (default)'), (3, 'Netherlands - DSMR version 2/3'), (101, 'Belgium - Fluvius (gas meter fix)'), (102, 'Luxembourg - Smarty (single tariff fix)'), (103, 'Sweden - Unknown (single tariff fix)')], default=4, help_text='The DSMR version your meter supports. Version should be printed on meter.', verbose_name='DSMR version'),
        ),
    ]
